services:
  web:
    env_file:
      - .env
    build: .
    container_name: web
    volumes:
      - ./app:/app
    expose:
      - "8000"
    links:
      - db

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
  db:
    env_file:
      - .env
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d